baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'lab-website-theme'
[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'People'
    pageRef = '/people'
    weight = 20
  [[menus.main]]
    name = 'Publications'
    pageRef = '/publications'
    weight = 30
  [[menus.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 40