baseURL = 'https://cda-lab.org/'
languageCode = 'en-us'
title = 'Halely Balaban | The CDA Lab'
theme = 'lab-website-theme'
[menus]
  [[menus.main]]
    name = 'HOME'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'PEOPLE'
    pageRef = '/people'
    weight = 20
  [[menus.main]]
    name = 'PUBLICATIONS'
    pageRef = '/publications'
    weight = 30
  [[menus.main]]
    name = 'CONTACT'
    pageRef = '/contact'
    weight = 40